version: '3'

services:
  bind9:
    image: resystit/bind9
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./named.conf:/etc/bind/named.conf:ro
      - ./example.com.db:/etc/bind/example.com.db:ro
